apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapplication22-deployment
  labels:
    app: member_api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member_api  
  template:
    metadata:
      labels:
        app: member_api
    spec:
      containers:
      - name: lmsapi001
        image: lmsapi001.azurecr.io/member_container:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: member_apisvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: member_api